### ISSUE TITLE
Unable to build xcbuild.

### ISSUE THREAD

**Issue by Ankit8946** [facebook/xcbuild#103]
I am unable to build xcbuild and getting the following error.

Ankit-Srivastava-iOS:xcbuild ankit$ make
mkdir -p build
cmake -Bbuild -H. -G Ninja -DCMAKE_INSTALL_PREFIX=
make: cmake: No such file or directory
make: *** [all] Error 1

**Comment by modocache** [comment]
The README states that CMake and Ninja are required to build. If you have Homebrew installed, you can try running `brew install cmake ninja` on the command line, then trying `make` again.

**Comment by Ankit8946** [comment]
Thanks.. That worked. Sorry I am new to all this. :/

**Comment by modocache** [comment]
No problem! 👍
