### ISSUE TITLE
Legacy builds don't build the first target when unspecified

### ISSUE THREAD

**Issue by ljysdfz** [facebook/xcbuild#110]
I had followed the tips in home page of xcbuild and make successfully
Then I input this at the command line to invoke a build:
`$ ./xcbuild -project ~/Desktop/Project/TestIOS/TestIOS.xcodeproj SYMROOT=~/Desktop`
with an absolutely vacuous output:

> Build settings from the command line:
>     SYMROOT=/Users/Robin/Desktop
> 
> ** BUILD SUCCEEDED **

But I cannot find any available intermediate files or production files in nowhere

thx for help ahead of time

**Comment by grp** [comment]
I think there's a bug where sometimes xcbuild doesn't detect any targets to build. Try `-alltargets` or `-target <name>`: I think that should convince it to start a build.
