### ISSUE TITLE
How can I resolve these errors?

### ISSUE THREAD

**Issue by hossainalhaidari** [facebook/xcbuild#115]
I've been trying to compile in ArchLinux and these errors appear:

$ ./xcbuild -workspace MyApp.xcworkspace -scheme MyScheme
error: couldn't find developer dir
error: couldn't create build environment

Any clues?

**Comment by grp** [comment]
I think this comment might help: https://github.com/facebook/xcbuild/issues/37#issuecomment-191858539 In short, xcbuild is a build system, but you still need a developer root (including toolchain and SDK) to build against, which aren't necessarily available on Linux yet.
