### ISSUE TITLE
xcbuild not work

### ISSUE THREAD

**Issue by senpng** [facebook/xcbuild#117]
```bash
$ ./build/xcbuild 
warning: unhandled Validation key AdditionalValidationClass
error: registering Architecture specification 'Standard' in domain iphonesimulator twice
error: registering Architecture specification 'i386' in domain iphonesimulator twice
error: registering Architecture specification 'x86_64' in domain iphonesimulator twice
error: registering Architecture specification 'Standard32_bit' in domain iphonesimulator twice
error: registering Architecture specification 'Universal64bit' in domain iphonesimulator twice
error: registering Architecture specification 'Native' in domain iphonesimulator twice
error: registering Architecture specification 'Standard' in domain iphoneos twice
error: registering Architecture specification 'armv7' in domain iphoneos twice
error: registering Architecture specification 'armv7s' in domain iphoneos twice
error: registering Architecture specification 'arm64' in domain iphoneos twice
error: registering Architecture specification 'Platform32_bit' in domain iphoneos twice
error: registering Architecture specification 'Platform64_bit' in domain iphoneos twice
error: registering Architecture specification 'Platform32_64_bit' in domain iphoneos twice
error: registering BuildSystem specification 'com.apple.build-system.native' in domain iphoneos twice
[1]    47231 segmentation fault  ./build/xcbuild
```
I don't solve this problem

**Comment by grp** [comment]
What version of Xcode do you have active? xcbuild hasn't been updated for Xcode 8 yet.

**Comment by senpng** [comment]
**Xcode Version:** _7.3.1 (7D1014)_

**Comment by grp** [comment]
Hmm, interesting, in my copy of Xcode 7.3.1 I don't see the keys mentioned in the output above. To confirm, that version is what you get from `xcodebuild -version` on your command line?

To debug further, you could enable logging for specification loading: change `Libraries/pbxspec/Sources/Manager.cpp` to say `#if 1` instead of `#if 0`. Then running `xcbuild` will print additional information about the files and specifications loaded.

**Comment by senpng** [comment]
```bash
$ xcodebuild -version
Xcode 7.3.1
Build version 7D1014
```
change `Libraries/pbxspec/Sources/Manager.cpp` all `#if 0` to `#if 1`, Then `make` and running `./build/xcbuild 2>&1 | tee debug.log`
**Log:**
[debug.log.zip](https://github.com/facebook/xcbuild/files/469431/debug.log.zip)

**Comment by grp** [comment]
Interesting! On your system, these files exist:

 - `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Specifications/*.xcspec`
 - `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Specifications/*.xcspec`

They're conflicting with these, which exist in both my system and yours:

 - `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/IDEiOSPlatformSupportCore.ideplugin/Contents/Resources/Simulator.xcspec`
 - `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/IDEiOSPlatformSupportCore.ideplugin/Contents/Resources/Device.xcspec`

Any idea where those files came from in your copy of Xcode? Maybe try re-downloading from the App Store?

**Comment by senpng** [comment]
I don't know those files, May be updated Xcode legacy？
I should be remove those files?
* `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/IDEiOSPlatformSupportCore.ideplugin/Contents/Resources/Simulator.xcspec`
* `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/IDEiOSPlatformSupportCore.ideplugin/Contents/Resources/Device.xcspec`

**Comment by grp** [comment]
I wouldn't modify it, but maybe try re-downloading Xcode?

**Comment by senpng** [comment]
Oh...Did you know that Xcode download very slow in China😂😂 ...
I try to re-download Xcode💪 ...
Thinks...You are the most handsome!👍👍👍👍

**Comment by grp** [comment]
You could try this to avoid re-downloading, but **make a backup copy of Xcode first** since it might break it:

    sudo rm -rf /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Specifications
    sudo rm -rf /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Specifications

**Comment by senpng** [comment]
6666666.....
Solved the problem!👍👍👍👍👍👍👍👍

**Comment by grp** [comment]
Cool, glad it worked!
