### ISSUE TITLE
Alternate way to specify developer root

### ISSUE THREAD

**Issue by narissiam** [facebook/xcbuild#120]
xcrun.xcbuild does the following to get the developer root:
```
ext::optional<std::string> Environment::
DeveloperRoot(Filesystem const *filesystem)
{
    if (char *path = getenv("DEVELOPER_DIR")) {
        return ResolveDeveloperRoot(filesystem, path);
    }

    if (auto path = filesystem->readSymbolicLink("/var/db/xcode_select_link")) {
        return path;
    }

    if (auto path = filesystem->readSymbolicLink("/usr/share/xcode-select/xcode_dir_path")) \
{
        return path;
    }
```
/var/db/xcode_select_link and /usr/share/xcode-select/xcode_dir_path require root perms to setup. Without these all invocations of xcrun have to set DEVELOPER_DIR. Can we slot in (after checking DEVELOPER_DIR env var) a check for ~/.xcsdk/xcode_dir_path ?

**Comment by grp** [comment]
Sure. Could this be stored inside the `~/.xcsdk/xcsdk_configuration.plist` configuration file?

**Comment by narissiam** [comment]
I wanted a feeler on the better approach: a xcsdk_configuration.plist value (something @Ktwu also suggested) or the ~/.xcsdk/xcode_dir_path symlink. My only concern for the plist value is the overhead of parsing a plist vs using the symlink. It's probably trivial in most use cases, though.

**Comment by grp** [comment]
It also might be a more complex change since the `DeveloperRoot()` method doesn't need a configuration right now. Maybe a symlink is better...

**Comment by sas** [comment]
The change with the symlink went in already.
