### ISSUE TITLE
 error: use of undeclared identifier '_CS_DARWIN_USER_CACHE_DIR'

### ISSUE THREAD

**Issue by FlyingNoob** [facebook/xcbuild#122]
When I excuse the make! I get an  error: use of undeclared identifier '_CS_DARWIN_USER_CACHE_DIR'

**Comment by grp** [comment]
Sorry — just pushed 288caf0577b2ccaa7bb485359a6941b3c01062a7 which should fix this.

cc @marcsalem, fixing #119 would help a lot with this.
