### ISSUE TITLE
Using std::call_once requires linking -lpthread

### ISSUE THREAD

**Issue by Ktwu** [facebook/xcbuild#139]
Using my Linux build of plutil crashes as soon as std::call_once is invoked.  The reason seems to be because -lpthread isn't linked (and, sure enough, adding this flag unblocks the tool).

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55394

**Comment by grp** [comment]
It's absurd this isn't a link-time error, at minimum. It should be pulled in automatically by linking the C++ standard library...
