### ISSUE TITLE
Fails to build Xcode 8 Swift project

### ISSUE THREAD

**Issue by bootstraponline** [facebook/xcbuild#159]
Success:
> xcodebuild -workspace A.xcworkspace -scheme B -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' build

Failure:
> xcbuild -workspace A.xcworkspace -scheme B -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' build

I'm using xcbuild from rev 49f8a5923f1381f87ac03ad4c1b138d1d2b74369 on Xcode 8. xcbuild appears to be unable to build any of our Swift projects. 😭 

```
** BUILD FAILED **

The following build commands failed:
    CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(1 failure)
```

**Comment by grp** [comment]
Xcode 8 is not fully supported yet. In particular, asset catalogs and Swift 3.0 have likely changed in ways that may not compile.

**Comment by grp** [comment]
Re-open if you have specific errors to investigate! Or command-lines for the `swiftc` invocation to compare between Xcode and xcbuild.

**Comment by grp** [comment]
Oh, `-destination` isn't supported in xcbuild yet either. You'll want to use `-sdk iphonesimulator` to target that. (I think this should warn during the build.)

**Comment by bootstraponline** [comment]
Great. Thanks for the info.
