### ISSUE TITLE
Does xcbuild pass environment variables through to programs it calls?

### ISSUE THREAD

**Issue by copumpkin** [facebook/xcbuild#194]
I'm seeing some weird behavior where `clang` and other build tools aren't seeing the environment I expect them to see, when they get invoked by `xcbuild`. I don't know if this replicates the `xcodebuild` behavior, but I'm wondering if it's intentional and if there's a way for me to control which environment variables get propagated to the programs being called.

**Comment by grp** [comment]
It generally does not, which I think is expected. There is a bug that `PATH` isn't set, though; see #169.

**Comment by copumpkin** [comment]
Ah I see. Is there some way I can ask `xcbuild` to pass certain variables along, perhaps by some spec hackery?

**Comment by grp** [comment]
In each tool spec there's an optional `EnvironmentVariables = { }` dictionary. The values in there are build setting expressions, so you can use `$(NAME)` to pass through a build setting. The environment is imported into the build settings so `"NAME" = "$(NAME)";` would pass it along, assuming it's not a build setting name overridden by something in xcbuild or another specification.

**Comment by copumpkin** [comment]
Oh, excellent! I think that's exactly what I want, thanks.
