### ISSUE TITLE
Implement -help command line option

### ISSUE THREAD

**Issue by grp** [facebook/xcbuild#2]
xcbuild has a `-help` option to explain the usage of the tool. Right now, this option is unimplemented.

To implement this, change `Driver.cpp` in `xcdriver` to call into `HelpAction::Run()`. Then, create a `HelpAction` class and implement the `Run()` method to print out usage info.

**Comment by g33kyaditya** [comment]
What all should be the usage information ? If I can have that, I could do this.

**Comment by modocache** [comment]
Sorry, @g33kyaditya, I ended up implementing this in 3272f72 -- I was looking for a starter task to get used to the codebase. Hope you don't mind!
