### ISSUE TITLE
Support "-version Path" in xcodebuild

### ISSUE THREAD

**Issue by matthewbauer** [facebook/xcbuild#204]
macOS xcodebuild seems to take options to "-version":

```
xcodebuild -version Path
```

This should output the SDK path.

This is seen in
https://github.com/qt/qtbase/blob/dev/configure#L271

## Update
This is actually mentioned in xcodebuild(1) man page:
```
xcodebuild -version [-sdk [sdkfullpath | sdkname]] [infoitem]
```

```
-version
Display version information for this install of Xcode. Does not
initiate a build. When used in conjunction with -sdk, the version
of the specified SDK is displayed, or all SDKs if -sdk is given no
argument.  Additionally, a single line of the reported version
information may be returned if infoitem is specified.
```

I cannot find any information on what "infoitem" but acceptable values seem to include:

* ProductVersion
* ProductBuildVersion
* Path

**Comment by grp** [comment]
The usage you listed shows `-version -sdk <path>` which is implemented. Do you have an example command that fails?

**Comment by grp** [comment]
However it looks like the `infoitem` parameters to `-version` aren't implemented. That would support printing out specific info about an SDK, I guess?
