### ISSUE TITLE
Support for plugins?

### ISSUE THREAD

**Issue by samdmarshall** [facebook/xcbuild#21]
Will this tool offer a simillar api for plugins? I am thinking of specifically plugins based on the xcspec files, while those are very few (I think I've written the only one) I do think it would be ideal for future compatibility and support during betas.

**Comment by wjk** [comment]
@samdmarshall That file format is (a variant of) the old, NeXT-style property list files. [There is already a parser for this format in xcbuild.](https://github.com/facebook/xcbuild/blob/master/Libraries/plist/Sources/Format/ASCIIParser.cpp) I disagree regarding sharing the directory between xcbuild and Xcode: what about Linux? I would probably prefer a `~/.xcbuild` directory or similar.

In addition, you don't need to load the plugin binaries to read the xcspec files out from within them; all you need to do is look in the plugin's `Contents/Resources` directory.

**Comment by samdmarshall** [comment]
@wjk Sorry, I wasn't clear with my initial phrasing: I am specifically talking about the syntactic rules that are evaluated inside of the plugin itself (see example [here](https://github.com/samdmarshall/citrus/blob/develop/CitrusPlugin/Lemon.xcspec#L20)). (to give you more context, I had written my own version of what xcbuild is trying to accomplish prior to the inception of this project 😊)

While true that the xcspec files could be loaded separate from the plugin binaries, in many cases with Xcode's own plugins this is not feasible as the binary augments the on-disk spec file. If we were to bypass loading the binary then it might as well be loading the xcspec file directly rather than use the bundle-based loading approach that is taken on OS X. I feel strongly that discarding that model would be a bad move for plugin support.
