### ISSUE TITLE
Ability to use other libplist library

### ISSUE THREAD

**Issue by seanfarley** [facebook/xcbuild#223]
Has anyone looked at using the existing library from http://www.libimobiledevice.org ? Just a thought for not duplicating code.

**Comment by grp** [comment]
Definitely considered it, but the license of that library (GPL or LGPL) isn't compatible with xcbuild. The Apple CoreFoundation is [now available under Apache 2.0](https://github.com/apple/swift-corelibs-foundation/) and would work in that respect, but it's not designed for integrating with C++. Microsoft has a [MIT-licensed C++ plist parsing library](https://github.com/Microsoft/PlistCpp), but I'm not sure how reusable the API design is. Ultimately, the current implementation seems to work well so far.

**Comment by seanfarley** [comment]
Ah, makes sense. Thanks for the explanation!
