### ISSUE TITLE
How to handle com.apple.product-type.library.static?

### ISSUE THREAD

**Issue by copumpkin** [facebook/xcbuild#228]
I'm currently building Libc-1082.50.1 from opensource.apple.com and `xcbuild` fails instantly with:

```
warning: unhandled Group key usesTabs
warning: unhandled Group key usesTabs
error: unable to find product type com.apple.product-type.library.static
error: couldn't create target environment for Variant_DarwinExtsn
```

I realize that Libc is tricky to build for other reasons (awkward private header setups, etc.), but this seems surmountable. Is there just a missing specification somewhere in the specification plists?

cc @grp @matthewbauer

**Comment by grp** [comment]
Yeah, it looks like you need the static library product type specification. The `usesTabs` warning should be ignorable since that's a UI setting.

**Comment by matthewbauer** [comment]
Here's a commit that should be compatible with latest nixpkgs:

https://github.com/matthewbauer/nixpkgs/commit/7849ace13b9ab0472741caa0ed8e5a212adc4741

You can ignore the -configuration Release part though.

**Comment by copumpkin** [comment]
@matthewbauer very cool! It throws me off a bit to see dylib mapped to
library.static though but perhaps that dylib part is a misnomer?

Also were you able to get static builds working with that?

Anyway I'll try with that specification and see if it helps, thanks!

**Comment by matthewbauer** [comment]
That might not be enough information for it to actually work- but it does get you farther into the build process. The dylib thing probably would be an issue eventually. We can add "com.apple.product-type.library.static" as ProductType and PackageTypes.

Take from the Xcode.app resources, here's a definition for com.apple.product-type.library.static:

```nix
   {
      Identifier = "com.apple.product-type.library.static";
      Type = "ProductType";
      Name = "Static Library";
      PackageTypes = [ "com.apple.package-type.static-library" ];
      DefaultBuildProperties = {
        FULL_PRODUCT_NAME = "$(EXECUTABLE_NAME)";
        MACH_O_TYPE = "staticlib";
        REZ_EXECUTABLE = "YES";
        EXECUTABLE_PREFIX = "lib";
        EXECUTABLE_SUFFIX = ".$(EXECUTABLE_EXTENSION)";
        EXECUTABLE_EXTENSION = "a";
        FRAMEWORK_FLAG_PREFIX = "-framework";
        LIBRARY_FLAG_PREFIX = "-l";
        LIBRARY_FLAG_NOSPACE = "YES";
        STRIP_STYLE = "debugging";
        SEPARATE_STRIP = "YES";
        CLANG_ENABLE_MODULE_DEBUGGING = "NO";
      };
   }
```

And here's another one for com.apple.package-type.static-library
```nix
    {
      Identifier = "com.apple.package-type.static-library";
      Type = "PackageType";
      Name = "Mach-O Static Library";
      DefaultBuildSettings = {
        EXECUTABLE_PREFIX = "lib";
        EXECUTABLE_SUFFIX = ".a";
        EXECUTABLE_NAME = "$(EXECUTABLE_PREFIX)$(PRODUCT_NAME)$(EXECUTABLE_VARIANT_SUFFI  ECUTABLE_SUFFIX)";
        EXECUTABLE_PATH = "$(EXECUTABLE_NAME)";
      };
      ProductReference = {
        FileType = "archive.ar";
        Name = "$(EXECUTABLE_NAME)";
        IsLaunchable = "NO";
      };
    }
```

(again it's not exactly clear what parts of the are needed to build and what are just GUI hints wanted by Xcode.app)

**Comment by grp** [comment]
I think this is an issue with your specs, so I'll close this here but might make sense to open on the Nix repo.

**Comment by copumpkin** [comment]
Yup, thanks!
