### ISSUE TITLE
actool fails with more than one asset catalog

### ISSUE THREAD

**Issue by jacobjennings** [facebook/xcbuild#231]
actool doesn't appear to accept more than one .xcassets file per invocation.

.../Images.xcassets .../Assets.xcassets: error: None of the input catalogs contained a matching app icon set named  "AppIcon".
/* com.apple.actool.notices */
.../Images.xcassets .../Assets.xcassets: warning: Failed to read file attributes for ".../Images.xcassets .../Assets.xcassets"
    Failure Reason: No such file or directory
/* com.apple.actool.compilation-results */

**Comment by grp** [comment]
Same as #214 I think.
