### ISSUE TITLE
Missing PBX types

### ISSUE THREAD

**Issue by samdmarshall** [facebook/xcbuild#24]
In the [ISA.cpp](../blob/master/Sources/pbxproj/ISA.cpp) file you seem to be missing the following PBX types:

```
PBXApplicationReference
PBXApplicationTarget
PBXBundleReference
PBXBundleTarget
PBXExecutableFileReference
PBXFrameworkReference
PBXFrameworkTarget
PBXJavaArchiveBuildPhase
PBXLibraryReference
PBXLibraryTarget
PBXRezBuildPhase
PBXStandAloneTarget
PBXToolTarget
PBXZipArchiveReference
```

**Comment by kphillisjr** [comment]
I know that `PBXRezBuildPhase` runs files specified in this through the Rez resource compiler.

**Comment by mkozjak** [comment]
`Xcodeproj doesn't know about the following attributes {"buildRules"=>[]} for the 'PBXAggregateTarget' isa. (RuntimeError)`
