### ISSUE TITLE
a problem in fast-rcnn 

### ISSUE THREAD

**Issue by arash111** [facebook/xcbuild#241]
Hi,
in the code proposed here (https://github.com/vlfeat/matconvnet/tree/master/examples/fast_rcnn), just wondering to know, how to obtain 000004_boxes.mat? I mean how can I create the .mat file for my own test image?

**Comment by sas** [comment]
I don't understand what this issue is about. Are you sure you posted it to the right location?

**Comment by arash111** [comment]
as I run the demo file (https://github.com/vlfeat/matconvnet/blob/master/examples/fast_rcnn/fast_rcnn_demo.m) in line 52 you would see: boxes = load('000004_boxes.mat') ;. it is mat file for test image (000004.jpg). just like to know how this '000004_boxes.mat' obtianed from '000004.jpg' image?

**Comment by sas** [comment]
You filed an issue for xcbuild. I think you want to file an issue in vlfeat/matconvnet.
