### ISSUE TITLE
CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.

### ISSUE THREAD

**Issue by heroims** [facebook/xcbuild#259]
ninja --version  is worked

[lookfe@troy xcbuild]$ make
which: no llbuild in (/home/lookfe/testIOS/ninja:/home/imgrec/anaconda2/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/lookfe/.local/bin:/home/lookfe/bin)
mkdir -p build
cmake -Bbuild -H. -G Ninja -DCMAKE_INSTALL_PREFIX= 
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /home/lookfe/testIOS/xcbuild/build/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: /home/lookfe/testIOS/xcbuild/build/CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake
-- Configuring incomplete, errors occurred!
make: *** [all] 错误 1
[lookfe@troy xcbuild]$ ninja --version
1.7.2
[lookfe@troy xcbuild]$ uname -a
Linux troy 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

It looks can't run in CentOS

**Comment by heroims** [comment]
It looks can't run in CentOS

**Comment by heroims** [comment]
It can run when I use cmake 3.9.1

**Comment by afshin-hoseini** [comment]
Sma issue

Cmake : 3.11.4
OS: Ubuntu 16.04

😢

**Comment by quguangle** [comment]
You need look Cmake version, The high version 3.10.1 I used Cmake before, Always reporting a mistake，Finally, I changed to 3.6.x and compiled successfully.

**Comment by andr3aLucch3si85** [comment]
Same problem!! CMake 3.13.4 and Ninja 1.9.0.
Help me please!!

**Comment by bboywindy** [comment]
in windows System. build android studio project is not successful. please help me .

CMAKE SERVER: CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMAKE SERVER: CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMAKE SERVER:

**Comment by lvp305703574** [comment]
You can try find cmake\3.10.2.4988404\bin path in your Android SDK directory.There is a ninja.exe file.
