### ISSUE TITLE
win32, bom_context_memory_file is broken

### ISSUE THREAD

**Issue by dkimitsa** [facebook/xcbuild#268]
1. on windows it will not work on zero length files, so there is workaround should be introduced in forcing minsize to 1   
>An attempt to map a file with a length of 0 (zero) fails with an error code of ERROR_FILE_INVALID. Applications should test for files with a length of 0 (zero) and reject those files.

2.
https://github.com/facebook/xcbuild/blob/34e535ea7dc38fd77f4927c4b9cb387643c7988e/Libraries/libbom/Sources/bom_memory.c#L174
if it fails check should be done against null, not INVALID_HANDLE_VALUE

**Comment by dkimitsa** [comment]
same thing is here 
https://github.com/facebook/xcbuild/blob/34e535ea7dc38fd77f4927c4b9cb387643c7988e/Libraries/libbom/Sources/bom_memory.c#L92

**Comment by sas** [comment]
Fixed with PR #271. Thanks for the report!
