### ISSUE TITLE
win32, ReadFile and WriteFile crashes on Windows7 due NPE

### ISSUE THREAD

**Issue by dkimitsa** [facebook/xcbuild#269]
both lpNumberOfBytesRead and lpOverlapped are null, but per doc 

NumberOfBytesRead [out, optional]
This parameter can be NULL only when the lpOverlapped parameter is not NULL.

PS: it works on Windows10 but crashes on W7

**Comment by sas** [comment]
Fixed with PR #272. Thanks for the report!
