### ISSUE TITLE
print "usage" for unknown arguments

### ISSUE THREAD

**Issue by umlaeute** [facebook/xcbuild#274]
after installing `xcbuild` (via [homebrew](https://github.com/thii/homebrew-xcbuild))I was kind of lost: whatever I tried would result in an `unknown argument` error:

~~~sh
$ xcbuild -h
error: unknown argument -h
$ xcbuild --help
error: unknown argument --help
$ man xcbuild
No manual entry for xbuild
$
~~~

only after searching the sources(sic!), i discovered that in order to get help i must specify `-help` (with a single dash).
Now I understand that single-dash arguments are somewhat standard with macOS. Unfortunately I'm coming from a GNU world (with single-dash short options and double-dash long options).

I think it would be very nice if:
- any unknown argument would (in addition to triggering the `unknown argument %s` message) be redirected to `-usage`.
- include `xcbuild -help` in the usage examples (probably at the very end).

**Comment by sas** [comment]
Agreed. I don't have time to deal with this right now, but if somebody ends up submitting a PR I'll gladly accept it.
