### ISSUE TITLE
Could xcbuild run iOS UITest on Ubuntu?

### ISSUE THREAD

**Issue by tianyig** [facebook/xcbuild#286]
Could xcbuild run iOS UITest on Ubuntu? Is anyone  test it???

**Comment by Ktwu** [comment]
Unfortunately no, xcbuild can't run UITests on Ubuntu -- those tests at the very least need to link against the XCTest framework, which xcbuild does not provide.

You'd also need libraries for each of the frameworks your UI test links against -- which, once again, xcbuild doesn't provide (and I don't know where you'd find such libraries for use on Linux in the first place).
