### ISSUE TITLE
Implement -usage command line option

### ISSUE THREAD

**Issue by grp** [facebook/xcbuild#3]
xcbuild has a `-usage` option to explain the usage of the tool. Right now, this option is unimplemented.

To implement this, change `Driver.cpp` in `xcdriver` to call into `UsageAction::Run()`. Then, create a `UsageAction` class and implement the `Run()` method to print out usage info.

**Comment by chessgeek** [comment]
I implemented this option recently, and I'm working on the -help option too. Are there any differences between this and the xcodebuild -usage option that are notable, or is it basically just a giant copy-paste?

**Comment by grp** [comment]
I don't think so, although there are the extension options `-formatter`, `-executor`, and `-generate` which would be specific to xcbuild.

It is important to avoid copy/pasting directly from `xcodebuild`, since xcbuild is standalone, but a quick writeup of what the options do would be great!

**Comment by chessgeek** [comment]
Thanks man! I'll get to work. I'm just starting to really dig into your codebase (found this project, like, a day ago), so I thought implementing the help and usage options would make me really have to understand what services it offers. Seems like some real cool stuff..!
