### ISSUE TITLE
Ship as a gem (or via homwbrew) instead of only as source?

### ISSUE THREAD

**Issue by nap-sam-dean** [facebook/xcbuild#38]
Hi,

How difficult would it be to ship this as a gem instead of having to build from source? We already use xcpretty as a gem on our CI agents, and having a stable gem for this as well would make our lives much much easier :)

Another alternative might be homebrew like xctool?

Thanks,
Sam

**Comment by kastiglione** [comment]
Homebrew :+1:

**Comment by grp** [comment]
Homebrew would be great. Need to figure out how to avoid conflicting with Xcode's builtin tools, then should be easy to set up.

**Comment by grp** [comment]
Same as #66.
