### ISSUE TITLE
linux error: empty path for sdk manager

### ISSUE THREAD

**Issue by gmittal** [facebook/xcbuild#42]
I'm trying to build an Xcode project on a Linux machine with xcbuild successfully installed. 

This is the output I'm getting (xcbuild is located in the root directory of my machine):
```shell
$ ~/xcbuild/./build/xcbuild -project PROJECT.xcodeproj -scheme PROJECT
error: empty path for sdk manager
error: couldn't create SDK manager
error: couldn't create build environment
```

**Comment by grp** [comment]
See the discussion on #37 for more details. In essence, xcbulid is just the build system — you'll still need a toolchain (compiler, linker, etc) and SDK (headers and libraries to compile against). On OS X, this comes from Xcode; on Linux, there are a number of options.
