### ISSUE TITLE
Relative Path 

### ISSUE THREAD

**Issue by gaurav17281** [facebook/xcbuild#46]
- XCBuild is unable to parse project files that contain relative path without quote. 
- Also, there's no error indication of what is failing and where, making it hard to debug. 

e.g. 
FAILURE - **path = ../Test/MyTestFile.m;**
SUCCESS - **path = "../Test/MyTestFile.m";**

Error - 
project.pbxproj is not parseable: Expected entry separator or array end; found something else

**Comment by grp** [comment]
Could you try with the latest master? I think https://github.com/facebook/xcbuild/commit/54642a85641367b755474d6afa4dc547a3e6112e will help with this.

**Comment by gaurav17281** [comment]
Thanks @grp. I'll try and report back.

**Comment by gaurav17281** [comment]
Works in the latest. Thanks much!

**Comment by grp** [comment]
Cool, glad it worked.
