### ISSUE TITLE
impression.h not found?

### ISSUE THREAD

**Issue by oliverhu** [facebook/xcbuild#48]
It builds in Mac OS El Capitan but nor working under Yosemite:

```
../Libraries/libcar/Sources/Rendition.cpp:21:10: fatal error: 'compression.h' file not found
#include <compression.h>
```
Got this error when trying to build xcbuild

**Comment by grp** [comment]
Sorry about that, an El Capitan only API was added unconditionally. It should be fixed now to build on Yosemite as well.
