### ISSUE TITLE
CMake error add_subdirectory(ThirdParty/googletest/googletest)

### ISSUE THREAD

**Issue by g33kyaditya** [facebook/xcbuild#61]
The add_subdirectory() in the top level CMakeLists.txt calls for the inclusion of /path/to/project/ThirdParty/googletest/googletest, but there is no such direcory. BUILD_TESTING should be ON to see the effect.

**Comment by strager** [comment]
You need to update Git's submodules for this directory to be non-empty.

From the README:
```
git clone https://github.com/facebook/xcbuild
cd xcbuild
git submodule update --init
```

@grp, perhaps CMake should detect if the submodule was not cloned and error out with a better diagnostic?
