### ISSUE TITLE
bug: target should be a tuple.

### ISSUE THREAD

**Issue by kphillisjr** [facebook/xcbuild#63]
The target argument with the stock xcodebuild utility works as a tuple when it has repeated entries. A valid example of how this works can be accomplished by trying to build a couple of the commonly used dtrace utilities.

```sh
# Download dtrace version 168 from apple.
curl -O https://opensource.apple.com/tarballs/dtrace/dtrace-168.tar.gz
tar zxf dtrace-168.tar.gz
cd dtrace-168
mkdir -p obj sym dst
# build ctfconvert, ctfdump, and ctfmerge targets using one command.
xcodebuild -target ctfconvert -target ctfdump -target ctfmerge ARCHS="x86_64" SRCROOT=$PWD OBJROOT=$PWD/obj SYMROOT=$PWD/sym DSTROOT=$PWD/dst
# Install (and build) ctfconvert, ctfdump, and ctfmerge targets using one command.
xcodebuild install -target ctfconvert -target ctfdump -target ctfmerge ARCHS="x86_64" SRCROOT=$PWD OBJROOT=$PWD/obj SYMROOT=$PWD/sym DSTROOT=$PWD/dst
```

**Comment by grp** [comment]
The dtrace project still doesn't build after the fix. It looks like there are three issues:

 1. `SDKROOT` isn't set by the project, but `SUPPORTED_PLATFORMS` is, which isn't handled. Can get past this by setting `SDKROOT` manually.
 2. The target build order is wrong. It looks like the project is underspecifying target dependencies, in that the executable targets have `-l` flags in `OTHER_LDFLAGS` for products they don't depend on. Or, perhaps there's a missing implicit dependency.
 3. The linker search paths don't include `$(SYMROOT)/$(CONFIGURATION)`, which is needed to find the linked libraries. (It's unclear to me why they should include that path without specifying it.)
