### ISSUE TITLE
xcbuild: add linux SDK Definition

### ISSUE THREAD

**Issue by kphillisjr** [facebook/xcbuild#67]
Due to the nature of how xcbuild works I figured it would not hurt to allow developers to compile various projects to run on linux directly. Some of these might take more work than others, but a few examples of projects that should have the ability to be compiled under linux with slight modification is as follows... 

- Apple cctools - http://opensource.apple.com/tarballs/cctools/cctools-877.8.tar.gz
- clang (with apple changes)- http://opensource.apple.com/tarballs/clang/clang-700.1.81.tar.gz
- ld64 - http://opensource.apple.com/tarballs/ld64/ld64-253.9.tar.gz
- bootstrap_cmds - http://opensource.apple.com/tarballs/bootstrap_cmds/bootstrap_cmds-93.tar.gz
- developer_cmds - http://opensource.apple.com/tarballs/developer_cmds/developer_cmds-62.tar.gz
- dtrace - http://opensource.apple.com/tarballs/dtrace/dtrace-168.tar.gz

**Comment by matthewbauer** [comment]
"ibtool" is also needed for most projects. I don't think any open source projects exist with that functionality.

**Comment by grp** [comment]
Microsoft's Xib2Nib increments part of ibtool functionality, although not a compatible CLI.
