### ISSUE TITLE
xcrun sets SYSROOT but prints SDKROOT

### ISSUE THREAD

**Issue by strager** [facebook/xcbuild#82]
I noticed this while looking at xcrun's source code:

                environment["SYSROOT"] = target->path();

                if (log) {
                    printf("env SDKROOT=%s %s\n", target->path().c_str(), executable->c_str());
                }

https://github.com/facebook/xcbuild/blob/master/Libraries/xcsdk/Tools/xcrun.cpp#L415-L423

The first line sets SYSROOT, but the log says SDKROOT. Which one is correct? Is this a bug?

**Comment by grp** [comment]
`SDKROOT` is correct. This is a bug.
