### ISSUE TITLE
installing xcbuild fails with cmake error: "Could NOT find PNG"

### ISSUE THREAD

**Issue by michaeleiselsc** [facebook/xcbuild#86]

**Comment by michaeleiselsc** [comment]
~/Developer/xcbuild on master
$ make
mkdir -p build
cmake -Bbuild -H. -G Ninja -DCMAKE_INSTALL_PREFIX=
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPNG.cmake:121 (find_package_handle_standard_args)
  Libraries/acdriver/CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/michael/Developer/xcbuild/build/CMakeFiles/CMakeOutput.log".
make: *** [all] Error 1

**Comment by michaeleiselsc** [comment]
was fixed by installing libpng. feel free to close, although it seems the user should be told to install libpng first

**Comment by grp** [comment]
I agree; especially on OS X it's less common to manually install dependencies. @marcsalem had some ideas here, or #83 could help.

**Comment by michaeleiselsc** [comment]
we could also just add something to the readme, right next to where we tell them to install other stuff

**Comment by grp** [comment]
I put up #87 to use built-in OS X libraries and avoid the dependency there.

**Comment by grp** [comment]
libpng is no long required on OS X, so this shouldn't come up there.
