### ISSUE TITLE
Implement PlistBuddy for non-OSX Platforms

### ISSUE THREAD

**Issue by kphillisjr** [facebook/xcbuild#89]
This is not exactly a commonly used tool, but this tool is especially important since it enables shell scripts to modify Property List files from the command line with ease. To get a general idea on how this utility works, look at the Apple [Mac OS X Manual Page: PlistBuddy(8)](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/PlistBuddy.8.html). I also know that there is a blog post titled "[OSX: Dealing with property list files](http://blog.eexit.net/osx-dealing-with-property-list-files/)" that can help with this.

Also as a quick note, on OSX this utility is installed as... /usr/libexec/plistbuddy

**Comment by grp** [comment]
Done with #111.
